# Generated by Django 5.0.6 on 2024-06-26 18:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=150)),
                ('everApplied', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=50)),
                ('procedure', models.CharField(max_length=100)),
                ('appointmentDate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
