# Generated by Django 5.0.6 on 2024-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0003_blogposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricedItem', models.CharField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
