# Generated by Django 5.0.6 on 2024-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0004_pricinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docImage', models.ImageField(upload_to='doctorsImage/')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pricinglist',
            name='pricedItem',
            field=models.CharField(max_length=200),
        ),
    ]
