# Generated by Django 5.0.6 on 2024-07-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0005_doctorslist_alter_pricinglist_priceditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='everApplied',
            field=models.CharField(max_length=50),
        ),
    ]
