# Generated by Django 5.0.6 on 2024-07-01 15:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0008_alter_appointment_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='country_code',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
