# Generated by Django 5.0.6 on 2024-07-03 14:46

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0009_appointment_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
